name: Node.js Server Management

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  manage-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # Specify your Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Check if server.js is running
        id: pm2-check
        run: |
          if pm2 list | grep -q 'server'; then
            echo "Server is already running."
            echo "::set-output name=server_running::true"
          else
            echo "Server is not running."
            echo "::set-output name=server_running::false"
          fi

      - name: Manage server with PM2
        run: |
          if ${{ steps.pm2-check.outputs.server_running }}; then
            echo "Stopping and deleting current server process."
            pm2 stop server
            pm2 delete server
            echo "Restarting server with PM2 in force mode."
            pm2 start server.js --name server -f
          else
            echo "Starting server with PM2."
            pm2 start server.js --name server
          fi
          pm2 save

      - name: Display PM2 status
        run: pm2 status
